// This file is generated by tool/generateAst.js

export class ModuleDefinition {
  constructor(
    public readonly moduleName: Token,
    public readonly assignmentList: Object[],
    {
      tagDefault,
      imports,
    }: { tagDefault?: Token; imports?: SymbolsFromModule[] },
  ) {
    this.tagDefault = tagDefault;
    this.imports = imports;
  }
}
