// This file is generated by tool/generateAst.js

import { Token } from "./token.js";

export class ModuleDefinition {
  public readonly tagDefault?: Token;
  public readonly imports?: SymbolsFromModule[];
  constructor(
    public readonly moduleName: Token,
    public readonly assignmentList: Object[],
    {
      tagDefault,
      imports,
    }: { tagDefault?: Token; imports?: SymbolsFromModule[] },
  ) {
    this.tagDefault = tagDefault;
    this.imports = imports;
  }
}

export class SymbolsFromModule {
  constructor(
    public readonly globalModuleReference: GlobalModuleReference,
    public readonly symbolList: Asn1Symbol[],
  ) {}
}

export class GlobalModuleReference {
  constructor(public readonly reference: Token) {}
}

export class Asn1Symbol {
  constructor(public readonly reference: Reference) {}
}

export class Reference {
  public readonly isParameterized?: Boolean;
  constructor(
    public readonly reference: Token,
    { isParameterized }: { isParameterized?: Boolean },
  ) {
    this.isParameterized = isParameterized;
  }
}
