import { TokenType } from "./tokenType";

export const RESERVED_WORDS: { [key: string]: TokenType } = {
  AUTOMATIC: TokenType.Automatic,
  BEGIN: TokenType.Begin,
  BIT: TokenType.Bit,
  BOOLEAN: TokenType.Boolean,
  CHOICE: TokenType.Choice,
  CONTAINING: TokenType.Containing,
  DEFAULT: TokenType.Default,
  DEFINITIONS: TokenType.Definitions,
  END: TokenType.End,
  ENUMERATED: TokenType.Enumerated,
  EXPORTS: TokenType.Exports,
  FALSE: TokenType.False,
  FROM: TokenType.From,
  IMPORTS: TokenType.Imports,
  INTEGER: TokenType.Integer,
  NULL: TokenType.Null,
  OCTET: TokenType.Octet,
  OF: TokenType.Of,
  OPTIONAL: TokenType.Optional,
  SEQUENCE: TokenType.Sequence,
  SIZE: TokenType.Size,
  STRING: TokenType.String,
  TRUE: TokenType.True,
  UNIQUE: TokenType.Unique,
  WITH: TokenType.With,
} as const;
